CREATE TABLE IF NOT EXISTS projects (
  id CHAR(36) NOT NULL PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  category VARCHAR(80) NOT NULL,
  province VARCHAR(80) NOT NULL,
  district VARCHAR(100) NOT NULL,
  lead_entity VARCHAR(180) NOT NULL,
  status ENUM('Planeado', 'Em Execução', 'Concluído') NOT NULL DEFAULT 'Planeado',
  progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  budget_total_mzn DECIMAL(15, 2) NOT NULL DEFAULT 0,
  budget_raised_mzn DECIMAL(15, 2) NOT NULL DEFAULT 0,
  start_date DATE NOT NULL,
  target_date DATE NOT NULL,
  description TEXT NOT NULL,
  key_metric VARCHAR(180) NOT NULL,
  key_metric_achieved VARCHAR(180) NOT NULL,
  volunteer_spots INT UNSIGNED NOT NULL DEFAULT 0,
  volunteers_enrolled INT UNSIGNED NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_projects_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_projects_status_date (status, created_at),
  INDEX idx_projects_province (province, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;